import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Selfie.module.css'
import CameraPlaceholder from '../../components/camera-placeholder'
import TakePhoto from '../../components/take-photo'
import EventService from '../../service/event.service'
import { uuid } from 'uuidv4'
import { setEvent } from '../../redux/action'
import { useDispatch } from 'react-redux'

const Selfie: NextPage = () => {

    const router = useRouter()
    const { code } = router.query
    const dispatch = useDispatch()
    const [placeholder, setPlaceholder] = useState(true)
    const [backgroundPass, setBackgroundPass] = useState(false)
    // const { selfie } = useSelector((state: any) => state.global)

    const initialize = () => {

        let android_id = localStorage.getItem("android_id")
        if (!android_id) {
            android_id = uuid();
            localStorage.setItem("android_id", android_id)
        }

        const event_code = typeof code == 'string' ? code : Array.isArray(code) ? code[0] : null
        console.log(code, event_code)
        EventService.getEvent(event_code, android_id)
            .then((res) => {
                console.log('event data', res.data)
                if (res && res.data)
                    dispatch(
                        setEvent({
                            event: res.data.event,
                            business: res.data.business,
                            device_id: res.data.device_id
                        })
                    )
            })
            .catch((err) => {
                console.log(err)
            })
    }

    const transTakePhoto = () => {
        setPlaceholder(false)
    }

    useEffect(() => {
        initialize()
    }, [code])


    return (
        <div>
            <Head>
                <title>Share your selfie</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {placeholder ?
                    <CameraPlaceholder
                        action={transTakePhoto}
                    />
                    :
                    <TakePhoto

                    />
                }
            </main>
        </div>
    )
}

export default Selfie