import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import Paper from '@mui/material/Paper'
import InputBase from '@mui/material/InputBase'
import Divider from '@mui/material/Divider'
import IconButton from '@mui/material/IconButton'
import DirectionsIcon from '@mui/icons-material/Directions';
import { Box } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Event.module.css'

const ChooseEvent: NextPage = () => {

    return (
        <div className={styles.container}>
            <Head>
                <title>Share your selfie</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <Image
                    className={styles.logo}
                    alt="logo"
                    src="/images/logo.png"
                    width={160}
                    height={136}
                />

                <div className={styles.content}>
                    <div className={styles.event_label}>
                        Insert Event Code
                    </div>

                    <Paper
                        component="form"
                        sx={{
                            my: 2,
                            p: '2px 4px',
                            display: 'flex',
                            alignItems: 'center'
                        }}
                    >
                        <InputBase
                            sx={{ ml: 1, flex: 1 }}
                            placeholder="xxx-xxx"
                            inputProps={{ 'aria-label': 'event code' }}
                        />
                        <Divider sx={{ height: 28, m: 0.5 }} orientation="vertical" />
                        <IconButton color="primary" sx={{ p: '10px' }} aria-label="directions">
                            <DirectionsIcon />
                        </IconButton>
                    </Paper>

                    <div className={styles.or}>
                        OR
                    </div>

                    <Box sx={{ m: 4 }}>
                        <Image
                            className={styles.qrcode}
                            alt="qr"
                            src="/images/qr_code.png"
                            width={160}
                            height={160}
                        />
                    </Box>

                    <div className={styles.qr_label}>
                        Scan QR Code
                    </div>
                </div>

            </main>

        </div>
    )
}

export default ChooseEvent
