import { useEffect } from 'react'
import { useRouter } from 'next/router';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {

  const router = useRouter()

  const initialize = () => {
    let sEvent = localStorage.getItem("selfio-event")
    setTimeout(() => {
      if (sEvent) {
        const evt = JSON.parse(sEvent)
        router.push(`/event/${evt.code}`)
      }
      else
        router.push("event")
    }, 1000)
  }

  useEffect(() => {
    initialize()
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Share your selfie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        <Image
          alt="logo"
          src="/images/logo.png"
          width={160}
          height={136}
        />

        <div className={styles.logo_title} >
          SHARE YOUR SELFIE
        </div>

      </main>

    </div>
  )
}

export default Home
