
export default interface Event {
    id: number,
    code: string,
    name: string,
    owner_id: string,
    orientation: string,
    start_time: string,
    end_time: string,
    enable: number,
    countdown: number,
    countdown_time: number,
    preview: number,
    four_six: number,
    gif: number,
    boomerang: number,
    use_overlay: number,
    overlay1: string,
    overlay2: string,
    overlay3: string,
    overlay4: string,
    print_overlay: string,
    green_screen: number,
    h_value: number,
    s_value: number,
    b_value: number,
    green_background: string,
    share: number,
    whatsapp: number,
    sms: number,
    email: number,
    email_msg: string,
    email_subject: string,
    block_menu: number,
    password: string,
    screen_saver: number,
    screen_saver_time: number,
    printer: number,
    printer_ip: string,
    copy_limit: number,
    background: number,
    background_type: string,
    back_content: string
}

